name: Tests
run-name: ${{ github.actor }} is running tests
on:
  - merge
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.6','3.7','3.8','3.9']
    steps:
      - uses: actions/checkout@v3
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
        run:
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: lint with flake8
        run: |
          flake8 ./app
      - name: run pytest
        run: |
          pytest ./app/test